name: Deploy EC2

on:
  workflow_call:
jobs:
  deploy_ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: forum
