on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup-java:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v3.13.0
      with:
        distribution: zulu
        java-version: '17'
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: '${{ runner.os }}-maven-${{ hashFiles(''**/pom.xml'') }}'
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run package
      run: mvn package -DskipTests
    - name: Create docker image
      run: docker build -t forum-api .
